## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [19]:
import numpy as np

print("Enter an integer:")
n = input()
try:
    a = np.arange(0, int(n), dtype = np.int64)[::-1]
    print("Result:", a)
except (TypeError, ValueError):
    print('Non integer input value')


7
[6 5 4 3 2 1 0]


## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [24]:
print("Enter an integer:")
n = input()
try:

    a = np.diag(np.arange(0, int(n), dtype = np.int64)[::-1])
    print("Result:\n", a)
except (TypeError, ValueError):
    print('Non integer input value')



Enter an integer:
10
Result:
 [[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


## Задание 3
Решите систему уравнений:
* 4x + 2y + z = 4
* x + 3y = 12
* 5y + 4z = -3

In [46]:
from numpy import linalg
a = np.matrix([[4, 2, 1], [1,3,0], [5,0,4]])
print("Matrix of coefficients:\n", a)
b = np.array([4,12,-3]).reshape(3, 1)
print("Constant terms:\n",b)
x = linalg.solve(a, b)

print("Calculated unknowns:\n")
for name, var in zip(["x" , "y", "z"], x.tolist()):
    print(name,'=', var)

Matrix of coefficients:
 [[4 2 1]
 [1 3 0]
 [5 0 4]]
Constant terms:
 [[ 4]
 [12]
 [-3]]
Calculated unknowns:

x = [-1.559999999999999]
y = [4.52]
z = [1.1999999999999986]


## Задание 4
Вам подаются на вход два вектора a и b в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью NumPy.

In [63]:
v1 = np.random.rand(3)
v2 = np.random.rand(3)
print("Scalar product:", v1, " * ", v2, '=', np.dot(v1,v2))

Scalar product: [0.5551376  0.40890056 0.43405375]  *  [0.86687117 0.99259536 0.11640404] = 0.93763119221895
